### ISSUE TITLE
Roles Login and Registration

### ISSUE THREAD

**Issue by dammy23** [yumpee/yumpeecms#3]
How can i implement Login and registration for two or more roles in yumpee

**Comment by tinycall** [comment]
You can pass the value of the role_id in your registration form. This ID must match the id of the role that you wish to register and it must be set as a frontend (F) type.

<input type="hidden" role_id="1ade4555..." />

For login, users who have their record will be logged in anyway. You will only need to ensure they don't have access to the role protected page. Your other option may be to define separate themes and make their login url and home pages different. That way when a user logs in, they are only redirected to their appropriate home page.
