### ISSUE TITLE
Form Update and Delete

### ISSUE THREAD

**Issue by dammy23** [yumpee/yumpeecms#5]
How can i update or delete for record

**Comment by yumpee** [comment]
To implement an update use the same method for creating a record BUT now set your request field Id to the id of the record you want to update. E.g

`<input type="hidden" name="id" value="{{record_id}}" />`



To delete a record use the internal hook - reference frontend/controllers/HookController.php

```
`$.ajax({
url: '{yumpee_setting}custom_hook_url{/yumpee_setting}hook/forms/ad-agent-profile/delete/{{record_id}},
type: 'GET',
success: function (returndata) {
alert("The record has been deleted");

}
});`
```
