### ISSUE TITLE
Implementing Change Password

### ISSUE THREAD

**Issue by dammy23** [yumpee/yumpeecms#6]
How can i implement Change Password form in yumpee

**Comment by yumpee** [comment]
Extend User Profile form and then set the password field accordingly. 

(1) Either user the Profile form for users in frontend/themes/views/forms/form-profile  OR
(2) Extend a new form that extends from User Profile in Web->Forms. If you set the form to have the same variable name for password, then this will change the password. refer frontend/controllers/FormsController.php for for types processing.
